### ISSUE TITLE
Attempt to invoke virtual method error

### ISSUE THREAD

**Issue by km147** [SkyzohKey/react-native-apk#3]
Getting the following error when trying to install an apk:

> Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.PackageItemInfo.loadXmlMetaData(android.content.pm.PackageManager,java.lang.string)' on a null object reference

I'm using react-native-fs to download the apk to internal storage first.

Testing on a real Android device running version 7.1. It seems Android have changed the way you start intents from Android 7 onwards: https://stackoverflow.com/questions/39147608/android-install-apk-with-intent-view-action-not-working-with-file-provider/40131196 

Could this be the problem? 

I'm using react native version 0.55.4

**Comment by VacuumDecay** [comment]
I have created a pull request #4 to fix this issue for Android 7 and above. Unfortunately it now requires a little more configuration but it is explained in the readme. Perhaps @SkyzohKey could take a look at merging this

**Comment by SkyzohKey** [comment]
Merged your PR! Thanks for the contributions! I'd like to push more code but I'm really busy since some months and can't find time for side projects :/
